nteBEGIN;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE DOMAIN IF NOT EXISTS EMAIL AS TEXT CHECK ( value ~ '^[\w\-\.]+@([\w-]+\.)+[\w-]+$');

CREATE DOMAIN IF NOT EXISTS PASSWORD AS TEXT CHECK ( value ~ '^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{6,}$');

CREATE DOMAIN IF NOT EXISTS ZIPCODE AS text CHECK (
    -- 63000 à 63999
    VALUE ~ '63\d{3}' 
);

CREATE TABLE IF NOT EXISTS public."plate"(
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "subtitle" TEXT NULL,
  "description" TEXT NOT NULL,
  "image" TEXT NULL,
  "price" NUMERIC(5,2) NOT NULL,
  "slug" TEXT NULL,
  "created_at" timestamptz NOT NULL DEFAULT NOW()
)

CREATE TABLE IF NOT EXISTS public."blog"(
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" TEXT NOT NULL,
  "subtitle" TEXT,
  "description" TEXT NOT NULL,
  "image" TEXT NULL,
  "interaction" TEXT NULL,
  "slug" TEXT NULL,
  "created_at" timestamptz NOT NULL DEFAULT NOW()
)

CREATE TABLE IF NOT EXISTS public."delivery_area"(
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "city" TEXT NOT NULL,
  "zipcode" ZIPCODE NOT NULL,
  "price" NUMERIC(5,2) NOT NULL
)

CREATE TABLE IF NOT EXISTS public."associated_sale"(
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "subtitle" TEXT NULL,
  "description" TEXT NOT NULL,
  "image" TEXT NULL,
  "price" NUMERIC(5,2) NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT NOW()
)

CREATE TABLE IF NOT EXISTS public."plate_has_associated_sale"(
  "associated_sale_id" INTEGER REFERENCES public."associated_sale"("id"),
  "plate_id" INTEGER REFERENCES public."plate"("id"),
)



COMMIT;